server:
  port: 8082
  servlet:
    context-path: /dota
spring:
  rabbitmq:
    host: 10.60.1.198
    username: admin
    password: admin
    publisher-confirms: true
    virtual-host: /
    port: 5672
logging:
  config: classpath:log4j2.yml